position = 'left'
anchor_to_edges = true

margin.top = 3
margin.bottom = 3
margin.left = 5
margin.right = 0

height = 75


[[start]]
class = 'launcher'
type = 'custom'

[[start.bar]]
on_click = '!rofi -show drun'
label = ''
name = 'launcher'
type = 'button'

[[start]]
type = 'workspaces'

[start.name_map]
0 = ''
1 = ''
2 = ''
3 = ''
4 = ''
5 = ''
6 = ''
7 = ''
8 = ''
9 = ''

[[start]]
type = 'tray'

[[center]]
type = 'clock'
format = " %H:%M"

[[end]]
type = 'music'
player_type = 'mpris'
truncate = "end"
format = "  {title}  "
icons.play = ""
icons.pause = ""

[[end]]
type = "volume"
format = "{icon}"
volume_high = ""
volume_medium = "󰖀"
volume_low = "󰕿"
muted = "󰝟"
 

[[end]]
class = 'power_menu'
type = 'custom'

[[end.bar]]
on_click = 'popup:toggle'
label = ''
class = 'power-button'
name = 'power-btn'
type = 'button'

[[end.popup]]
class = 'power-btn-popup'
orientation = 'vertical'
type = 'box'


[[end.popup.widgets]]
type = 'box'

[[end.popup.widgets.widgets]]
class = 'power-btn'
on_click = '!shutdown now'
label = '''<span font-size='40pt'></span>'''
type = 'button'

[[end.popup.widgets.widgets]]
class = 'power-btn'
on_click = '!reboot'
label = '''<span font-size='40pt'></span>'''
type = 'button'

